/// Tags supported by Xiino.
/// Taken from HTMLSpecifications.txt
pub const SUPPORTED_TAGS: [&str; 77] = [
    "a",
    "address",
    "area",
    "b",
    "base",
    "basefont",
    "blink",
    "blockquote",
    "body",
    "bgcolor",
    "br",
    "clear",
    "center",
    "caption",
    "cite",
    "code",
    "dd",
    "dir",
    "div",
    "dl",
    "dt",
    "font",
    "form",
    "frame",
    "frameset",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "hr",
    "i",
    "img",
    "input",
    "isindex",
    "kbd",
    "li",
    "map",
    "meta",
    "multicol",
    "nobr",
    "noframes",
    "ol",
    "option",
    "p",
    "plaintext",
    "pre",
    "s",
    // xiino's js support is very limited by modern standards, and is thus disabled
    //"script",
    "select",
    "small",
    "strike",
    "strong",
    "style",
    "sub",
    "sup",
    "table",
    "td",
    "th",
    "tr",
    "tt",
    "u",
    "ul",
    "var",
    "xmp",
    "wbr",
    // additional header tags not specified but known or assumed to be supported
    "head",
    "title",
    // "link",
    "base",
    "meta",
    // "Core" tags
    "html",
    "body",
    // Begrudging guests that doesn't seem to hurt Xiino but breaks OpenXiino
    "span",
    "main",
    "section",
    "thead",
    "tbody",
];
